### ISSUE TITLE
Updater causes "OSError: [Errno 9] Bad file descriptor"

### ISSUE THREAD

**Issue by Danilka** [karolyi/py3-validate-email#10]
I'm using a pipenv to run my project's environment in Ubuntu with supervisor.
On start, I'm getting OSError: [Errno 9] Bad file descriptor pointing to line 89 in updater.py
`with open(self._lock_file_path) as fd:`
Adding a simple 'w' helped resolve the issue.
`with open(self._lock_file_path, 'w') as fd:`
Can we add this to the library or am I missing something?

**Comment by karolyi** [comment]
Hey,

thanks for the report. I'm actually in the process of giving a huge update to the autoupdater which will address this problem as well.

A release will probably happen today if all goes well, and you can test if you still get any errors from the updater.

**Comment by karolyi** [comment]
This issue should have been fixed upwards of `0.2.5`, please try it out and give a feedback if it works for you.
