### ISSUE TITLE
Handling of email address using a literal IP address instead of a domain name is inconsistent

### ISSUE THREAD

**Issue by reinhard-mueller** [karolyi/py3-validate-email#12]
I noticed a small inconsistency, which I consider not urgent or important at all, but still wanted to note it:

While the 'regex' checker spends extra effort for accepting email addresses lke `example@[1.2.3.4]` as well, the 'mx' checker will refuse such addresses because the dns lookup will find no domain server for [1.2.3.4].

**Comment by karolyi** [comment]
Again, PR welcomed :)

**Comment by reinhard-mueller** [comment]
FWIW, I'm going look into this soon, but I first need to find a server which actually accepts emails by the ip address notation so I can test this.
