### ISSUE TITLE
How do I debug timeouts?

### ISSUE THREAD

**Issue by dfrankow** [karolyi/py3-validate-email#18]
Thanks for your library.

I tried it with a simple email I know exists, and it timed out as follows:

```
$ echo "valid.email@example.com" | ./validate_emails.py 
Validation for 'valid.email@example.com' failed: Email address undeliverable:
ASPMX3.GOOGLEMAIL.com.: timed out
ASPMX2.GOOGLEMAIL.com.: timed out
ALT1.ASPMX.L.GOOGLE.com.: timed out
ASPMX.L.GOOGLE.com.: timed out
ALT2.ASPMX.L.GOOGLE.com.: timed out
```

My call is straight from the docs:

```
        is_valid = validate_email(
            email_address=the_email,
            check_regex=True,
            check_mx=True,
            from_address='valid.email@example.com',
            helo_host='smtp.gmail.com',
            smtp_timeout=1,
            dns_timeout=1,
            use_blacklist=True)
```

How do I further debug this?

It may well be a firewall somewhere, but I can't tell where those hosts come from, or which line is timing out.

**Comment by dfrankow** [comment]
FYI, I seem to be able to do an MX check from the command line (see below), and a colleague can run my code successfully from his machine.

I'm using OS X 10.14 if that matters.

```
$ nslookup -q=MX gmail.com
Server:		192.168.0.1
Address:	192.168.0.1#53

Non-authoritative answer:
gmail.com	mail exchanger = 20 alt2.gmail-smtp-in.l.google.com.
gmail.com	mail exchanger = 30 alt3.gmail-smtp-in.l.google.com.
gmail.com	mail exchanger = 5 gmail-smtp-in.l.google.com.
gmail.com	mail exchanger = 40 alt4.gmail-smtp-in.l.google.com.
gmail.com	mail exchanger = 10 alt1.gmail-smtp-in.l.google.com.

Authoritative answers can be found from:
gmail.com	nameserver = ns1.google.com.
gmail.com	nameserver = ns3.google.com.
gmail.com	nameserver = ns2.google.com.
gmail.com	nameserver = ns4.google.com.
alt2.gmail-smtp-in.l.google.com	internet address = 64.233.177.27
alt3.gmail-smtp-in.l.google.com	internet address = 173.194.66.26
alt4.gmail-smtp-in.l.google.com	internet address = 173.194.212.26
ns1.google.com	internet address = 216.239.32.10
ns1.google.com	has AAAA address 2001:4860:4802:32::a
ns2.google.com	has AAAA address 2001:4860:4802:34::a
ns3.google.com	has AAAA address 2001:4860:4802:36::a
ns4.google.com	has AAAA address 2001:4860:4802:38::a
```

**Comment by karolyi** [comment]
If you mean testing connections to these email servers, you can do that with telnet.

Basically for example, `telnet alt1.aspmx.l.google.com 25` and see what happens.

On the other hand, I don't see how this is a bug of the library.

**Comment by dfrankow** [comment]
It's not a bug. It's an "issue" or a "feature request": what more information can I get from this library about exactly which call is failing? I can't find any debug logging, or any docs, or anything. I'm tracing through the library, but there's a lot there.

Even your suggestion may be helpful. The connection is refused, so maybe that indicates a firewall blocking outgoing connections.

**Comment by karolyi** [comment]
One idea is to subclass python's SMTP library and override the `set_debuglevel` method which originally prints to `stderr`, and make it log to `logger.debug`, the output of which you can write to a file to look up later.

I might look into this later.

**Comment by dfrankow** [comment]
I see, I can use [this line from here](https://github.com/karolyi/py3-validate-email/blob/master/validate_email/mx_check.py#L82) and turn up the debuglevel.

```
    smtp.set_debuglevel(debuglevel=0)
```

That's what I wanted. Thanks! You can close this now.

I still don't know why I can't connect (or how to debug that), but at least I can see exactly what connections it tried to make.

**Comment by karolyi** [comment]
The problem with that is, it logs to stderr which is bad practice in the case of production environments. Hence my idea of making it log to logger, but I'm still unsure if it would make the smtp lib log about the connection errors. As far as I've seen it only logs protocol errors.

This might be a consideration for later, closing this now.

**Comment by dfrankow** [comment]
I'm fine with you closing it.

I think I discovered the problem: my ISP blocks both incoming and outgoing port 25. But, they offer their own SMTP server. So now I'd like to use their SMTP server for MX checks. Does this library support that? I don't see it. Should I file a different issue?

**Comment by dfrankow** [comment]
Or maybe that's HELO host? I'm a bit fuzzy on exactly what HELO host is. Is that the host that is contacted in order to check the MX record, or is the hostname given to the MX record checking host?

**Comment by karolyi** [comment]
The SMTP protocol doesn't support 'checking via a proxy' to my knowledge, so this library is not a target for it, and would make no sense to try to implement it.

The SMTP server your ISP offers is most probably just an SMTP server that's open for your IP range, and will act as an email relay.

**Comment by dfrankow** [comment]
Never mind. After further debugging, I think it'll be too complicated or impossible to use their email service, because unless I have an email with them, it looks like a relay, which they forbid.
