### ISSUE TITLE
Cannot verify my own address

### ISSUE THREAD

**Issue by paulamartingonzalez** [karolyi/py3-validate-email#22]
Thanks for the great work putting this together. I am having issues making it work, I did a first trial with my own email address and it returns that it cannot be validated. Can you please advise?

> from validate_email import validate_email
> is_valid = validate_email(email_address=my_gmail_address, check_regex=True, check_mx=True)

> Validation for my_email_address failed: Email address undeliverable:
> alt2.gmail-smtp-in.l.google.com.: [Errno 99] Cannot assign requested address
> alt3.gmail-smtp-in.l.google.com.: [Errno 99] Cannot assign requested address
> alt4.gmail-smtp-in.l.google.com.: [Errno 99] Cannot assign requested address
> gmail-smtp-in.l.google.com.: [Errno 99] Cannot assign requested address
> alt1.gmail-smtp-in.l.google.com.: [Errno 99] Cannot assign requested address

**Comment by karolyi** [comment]
Hey,
this to me seems that you have problems with the hostname resolution on your system. The host names in your error message (those are gmail.com MX records) can't be resolved to an IP address.

Please make sure the host resolution works, the module should work then too.

**Comment by hdanirwin** [comment]
@karolyi how would I troubleshoot host resolution? I'm thinking it might be my issue as well. 

Had a lot of trouble getting dnspython installed. Maybe its running, but not actually installed properly?

**Comment by karolyi** [comment]
If dnspython gives you proper responses (that is, resolves to IP addresses) from a python REPL, it must be your connection, that is either your ISP blocking port 25 access, or the receiving party blocking your IP with using blocklist services.

You can test dnspython by going to their module page, and looking up their API. It should be no big issue to test it within a quick python command line.
