### ISSUE TITLE
New feature needed: separate check_mx and check_email_exists

### ISSUE THREAD

**Issue by husisusi** [karolyi/py3-validate-email#23]
is it possible to separate check_mx to check just the MX record and not whether the email actually exists?

**Comment by karolyi** [comment]
You can use dnspython easily to check MX records, no need for this module to dissect functionality for it. Look at the source code for an example, but dnspython itself is pretty straightforward.

**Comment by husisusi** [comment]
But I want check E-Mail regex and MX at once, not just MX.

**Comment by karolyi** [comment]
For the email regex you can also use the validator you can find in this module.

Other than that, PR requests are welcome.

**Comment by husisusi** [comment]
It will be nice to have something like:
 is_valid = validate_email(email_address=(email_address), check_mx=True, check_regex=True, ,verify=False)
Just like validate_email. Of course I can use validate_email but py3-validate-email has more feature.
