### ISSUE TITLE
Cannot verify own email

### ISSUE THREAD

**Issue by ranishreee** [karolyi/py3-validate-email#24]
Replaced the previous validate-email package with py3-validate-email.
However, validate_email() returns None for my mail Id.

**Comment by karolyi** [comment]
you will need to provide a reproducible example for me to even try to take on this.

**Comment by ranishreee** [comment]
Thanks for the response.

is_valid = validate_email('bijaypc.das6@gmail.com',check_mx=True)
print(is_valid)

This returns None.

**Comment by karolyi** [comment]
Please update to the latest version `0.2.9` and run the test code here:

https://github.com/karolyi/py3-validate-email#my-email-doesnt-check-out
