### ISSUE TITLE
Feature Request: Get SMTP code /message

### ISSUE THREAD

**Issue by taewookim** [karolyi/py3-validate-email#25]
Why: Would like to know if my IP/server got blacklisted

**Comment by karolyi** [comment]
Elaborate please?

As per the SMTP result codes you either get a 4XX in which case you can retry later, or you get a 5XX when you are denied from further retries.

If you use the (somewhat new) https://github.com/karolyi/py3-validate-email/blob/63f4661fd3c8f9b838784754d472b8a072a2fef2/validate_email/validate_email.py#L14, you should get an `EmailValidationError` https://github.com/karolyi/py3-validate-email/blob/63f4661fd3c8f9b838784754d472b8a072a2fef2/validate_email/exceptions.py#L4 base class with the message that occurred on denial. You can go from there and see what the exact message was; but the message is for humans and not for machines to read, hence there is no simplistic way to tell if it was a blocklist error.

**Comment by karolyi** [comment]
The one with the message in the exception will be `AddressNotDeliverableError`:
https://github.com/karolyi/py3-validate-email/blob/63f4661fd3c8f9b838784754d472b8a072a2fef2/validate_email/mx_check.py#L97

**Comment by taewookim** [comment]
Sorry, my apologies. for some reason, github is not sending notifications to my inbox

AddressNotDeliverableError could be based on getting the IP listed in spamhaus. in such case, will 5XX be listed as the exception?

**Comment by karolyi** [comment]
You should get the rejection message as the exception message, yes.
