### ISSUE TITLE
Everything gets rejected (25)

### ISSUE THREAD

**Issue by matija2209** [karolyi/py3-validate-email#27]
I'm not sure I completely get the "Everything gets rejected" part. I have a custom email address on an SMTP host (Mailjet).

I've put 'helo_host' = 'in-v3.mailjet.com' and 'from_address' = 'my_custom_email_sent_from_helo_host' as well as opened port (25) to no avail. Any ideas?

**Comment by karolyi** [comment]
Hey,
could you please post the results of the debug log described [here](https://github.com/karolyi/py3-validate-email#my-email-doesnt-check-out)?
