### ISSUE TITLE
How many emails can be verefied at one stretch, I want to verify 4000 emails in a loop, is it possibe?

### ISSUE THREAD

**Issue by rahulsree7** [karolyi/py3-validate-email#28]

**Comment by Hamza-Lachi** [comment]
Hi, I have created an email validation system in python which is faster and more accurate

when you will register you will get 10,000 credits. 

you can validate your 10,000 emails in maybe 5 mins

you can try it:

https://emailvalidator.pawnhost.com/account/register/

**Comment by karolyi** [comment]
See https://github.com/karolyi/py3-validate-email#i-cant-check-thousands-of-emails

You can check as many as you want, but there can be repercussions.
Also, don't fall for other people's scam (the comment I deleted).
