### ISSUE TITLE
Please allow option to either disable "optional" blacklist or disable its output.

### ISSUE THREAD

**Issue by Silverlink34** [karolyi/py3-validate-email#33]
I use your module in a command-line utility I've written for our company, every time it starts we get the spitted out info for the blacklist check. We would really appreciate a way to disable this output.

See below: 
(note that the '::>' is all you are supposed to see. Its the 'promt' part of the utility but its being covered by the output of blacklist check. My users are confused because they think its still doing something and it is not.)

> (MainThread) Lock 2030992950160 acquired on C:\Users\BRANDO~1.GAL\AppData\Local\Temp\tmp-py3-validate-email-1\blacklistupdater.lock
> (MainThread) Lock 2030992950160 released on C:\Users\BRANDO~1.GAL\AppData\Local\Temp\tmp-py3-validate-email-1\blacklistupdater.lock
> (MainThread) Starting optional update of built-in blacklist.
> (Thread-1 ) Lock 2030993021976 acquired on C:\Users\BRANDO~1.GAL\AppData\Local\Temp\tmp-py3-validate-email-1\blacklistupdater.lock
> _________________________________________
>  ____ ____ ____ ____ ____ ____ ____ ____
> ||A |||l |||p |||h |||a |||C |||L |||I ||
> ||__|||__|||__|||__|||__|||__|||__|||__||
> |/__\|/__\|/__\|/__\|/__\|/__\|/__\|/__\|
> 
> _________________________________________
> Please enter your command. For a list of commands, use the  help  command.
> For help with a specific command, use  help commandName  .
> 
> ::>(Thread-1 ) Lock 2030993021976 released on C:\Users\BRANDO~1.GAL\AppData\Local\Temp\tmp-py3-validate-email-1\blacklistupdater.lock
> (Thread-1 ) Lock 2030992713376 acquired on C:\Users\BRANDO~1.GAL\AppData\Local\Temp\tmp-py3-validate-email-1\blacklistupdater.lock
> (Thread-1 ) Lock 2030992713376 released on C:\Users\BRANDO~1.GAL\AppData\Local\Temp\tmp-py3-validate-email-1\blacklistupdater.lock
>

**Comment by karolyi** [comment]
Hey,

this comes from the file locking module, not from our updater (a module that the updater is using).

Can you tell me what logging settings you use? Per default, no one is supposed to see these lines, as it's internal to the filelock module.

**Comment by Silverlink34** [comment]
I dont have any logging settings set. So the default

**Comment by Silverlink34** [comment]
This is all my code does with the module:

from validate_email import validate_email

def checkEmail(*emails):
 invalidEmails = []
 validEmails = []
 for email in emails:
  if '@yahoo.com' in email:
   print(colored("NOTE: This tool will not be able to check Yahoo emails.
Yahoo's mail server unfortunately reports any @yahoo.com email as valid
until an actual email is sent to it.",'white','on_red'))
   print(colored(email,'white','on_red'))
   continue

  emailIsValid = validate_email(email_address=email, check_regex=True,
check_mx=True, from_address='alphacli@alink.com', helo_host='
officemail.alink.com', smtp_timeout=5, dns_timeout=5, use_blacklist=True,
debug=False)
  if emailIsValid:
   validEmails.append(email)
  else:
   invalidEmails.append(email)

 print(colored('Valid Emails:','yellow'))
 print(colored(validEmails,'green'))
 print('')
 print(colored('Invalid Emails:','yellow'))
 print(colored(invalidEmails,'red'))

**Comment by karolyi** [comment]
Hey,

I've just released 0.2.11, where I've changed the logging to only emit `debug()` messages instead of `info()` and warnings when `debug=True` is passed.

The ones the `Filelock` module emits, I have no control over. When looking into its source, I saw they use `LOGGER.info()` to emit some debug logging.

I don't know what logging setup your `colored()` function (or the module that contains it) does, but even if my module itself doesn't emit messages you don't want to see, you can try and change the default logging settings at startup so you skip the `.info()` logs the locking module emits.

This way, you could achieve the desired outcome of having absolutely no logs emitted on stdout.

**Comment by Silverlink34** [comment]
I'm not familiar with the logging modules, I typically just print using
default print module. The colored module is a submodule of termcolor.
Allows for some pretty output.

I am not sure if something within those modules is goofing up the Filelock
module you mentioned.

You don't have to give me the direct answer if you don't have it handy,
what logging module should I look up so I can figure out how to change the
default logging settings at the beginning of my script?

**Comment by karolyi** [comment]
It's the one in python: https://docs.python.org/3/library/logging.html

If you search around on the internet, you'll find examples on stackoverflow about how to add filters to the logging to filter out the Filelock logging.

**Comment by Silverlink34** [comment]
Ok! Thank you sir for your help, for identifying that the problem isn't
with your module, and pointing me in the right direction to resolve my
specific case. Much appreciated!!
