### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by cmorsucci** [karolyi/py3-validate-email#35]
Can anyone help me?

`ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-dwzlwitn/py3-validate-email/setup.py'"'"'; __file__='"'"'/tmp/pip-install-dwzlwitn/py3-validate-email/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-cf1xq5b4
         cwd: /tmp/pip-install-dwzlwitn/py3-validate-email/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-dwzlwitn/py3-validate-email/setup.py", line 19
        log.info(f'downloading blacklist to {BLACKLIST_FILEPATH_INSTALLED}')
                                                                          ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

**Comment by karolyi** [comment]
Hey,

what python version are you using ?

**Comment by cmorsucci** [comment]
Sorry, we close the ticket because I had not read that it is compatible with the python 3.6 version in fact after updating it works correctly, thanks
