### ISSUE TITLE
gamil detect fail 

### ISSUE THREAD

**Issue by dev-param** [karolyi/py3-validate-email#37]
Validation for 'me@gmail.com' failed: Email address undeliverable:
alt3.gmail-smtp-in.l.google.com: [Errno 99] Cannot assign requested address
alt1.gmail-smtp-in.l.google.com: [Errno 99] Cannot assign requested address
alt2.gmail-smtp-in.l.google.com: [Errno 99] Cannot assign requested address
gmail-smtp-in.l.google.com: [Errno 99] Cannot assign requested address
alt4.gmail-smtp-in.l.google.com: [Errno 99] Cannot assign requested address

**Comment by karolyi** [comment]
you'll have to give more context for me to respond on this. see https://github.com/karolyi/py3-validate-email#my-email-doesnt-check-out

**Comment by dev-param** [comment]
it work on linux with ip change

**Comment by dev-param** [comment]
how i use proxy for checking email

**Comment by karolyi** [comment]
This module is not designed to work with proxies. Your best bet is to connect to a VPN and test it that way.

**Comment by dev-param** [comment]
Please add proxy  support

**Comment by karolyi** [comment]
PRs are welcome.
