### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by diazardian** [karolyi/py3-validate-email#38]
![image](https://user-images.githubusercontent.com/17336685/102588066-6947f280-413f-11eb-87fe-5742e80255e5.png)
![image](https://user-images.githubusercontent.com/17336685/102588130-867cc100-413f-11eb-9855-ad847c20a14a.png)

**Comment by karolyi** [comment]
![image](https://user-images.githubusercontent.com/987055/102597019-46efae00-411a-11eb-8333-4f5a455c5962.png)
