### ISSUE TITLE
Every request is timing out. 

### ISSUE THREAD

**Issue by hdanirwin** [karolyi/py3-validate-email#39]
Every email I try and verify times out and then fails. Can't figure out what I'm doing wrong

Here is the output of the debugging:

```
 (venv) Hs-MacBook-Pro:pythonProject4 hdanforthirwin$ python -c 'import logging, sys; logging.basicConfig(stream=sys.stderr, level=logging.DEBUG); from validate_email import validate_email; print(validate_email("dan@retention360.com", check_mx=True, debug=True))'
DEBUG:filelock:Attempting to acquire lock 4523126688 on /var/folders/3j/cwnxk5xx3_g3lq398pxd041m0000gn/T/tmp-py3-validate-email-501/blacklistupdater.lock
INFO:filelock:Lock 4523126688 acquired on /var/folders/3j/cwnxk5xx3_g3lq398pxd041m0000gn/T/tmp-py3-validate-email-501/blacklistupdater.lock
DEBUG:validate_email.domainlist_check:(Re)loading blacklist from /Users/hdanforthirwin/PycharmProjects/pythonProject4/venv/lib/python3.9/site-packages/validate_email/data/blacklist.txt
DEBUG:filelock:Attempting to release lock 4523126688 on /var/folders/3j/cwnxk5xx3_g3lq398pxd041m0000gn/T/tmp-py3-validate-email-501/blacklistupdater.lock
INFO:filelock:Lock 4523126688 released on /var/folders/3j/cwnxk5xx3_g3lq398pxd041m0000gn/T/tmp-py3-validate-email-501/blacklistupdater.lock
DEBUG:validate_email.updater:Starting optional update of built-in blacklist.
DEBUG:filelock:Attempting to acquire lock 4531404608 on /var/folders/3j/cwnxk5xx3_g3lq398pxd041m0000gn/T/tmp-py3-validate-email-501/blacklistupdater.lock
INFO:filelock:Lock 4531404608 acquired on /var/folders/3j/cwnxk5xx3_g3lq398pxd041m0000gn/T/tmp-py3-validate-email-501/blacklistupdater.lock
DEBUG:validate_email.updater:Not updating because file is fresh enough.
DEBUG:filelock:Attempting to release lock 4531404608 on /var/folders/3j/cwnxk5xx3_g3lq398pxd041m0000gn/T/tmp-py3-validate-email-501/blacklistupdater.lock
INFO:filelock:Lock 4531404608 released on /var/folders/3j/cwnxk5xx3_g3lq398pxd041m0000gn/T/tmp-py3-validate-email-501/blacklistupdater.lock
DEBUG:filelock:Attempting to acquire lock 4531470592 on /var/folders/3j/cwnxk5xx3_g3lq398pxd041m0000gn/T/tmp-py3-validate-email-501/blacklistupdater.lock
INFO:filelock:Lock 4531470592 acquired on /var/folders/3j/cwnxk5xx3_g3lq398pxd041m0000gn/T/tmp-py3-validate-email-501/blacklistupdater.lock
DEBUG:validate_email.domainlist_check:(Re)loading blacklist from /Users/hdanforthirwin/PycharmProjects/pythonProject4/venv/lib/python3.9/site-packages/validate_email/data/blacklist.txt
DEBUG:filelock:Attempting to release lock 4531470592 on /var/folders/3j/cwnxk5xx3_g3lq398pxd041m0000gn/T/tmp-py3-validate-email-501/blacklistupdater.lock
INFO:filelock:Lock 4531470592 released on /var/folders/3j/cwnxk5xx3_g3lq398pxd041m0000gn/T/tmp-py3-validate-email-501/blacklistupdater.lock
DEBUG:validate_email.mx_check:Trying ALT1.ASPMX.L.GOOGLE.com ...
DEBUG:validate_email.mx_check:Trying ALT2.ASPMX.L.GOOGLE.com ...
DEBUG:validate_email.mx_check:Trying ASPMX2.GOOGLEMAIL.com ...
DEBUG:validate_email.mx_check:Trying ASPMX3.GOOGLEMAIL.com ...
DEBUG:validate_email.mx_check:Trying ASPMX.L.GOOGLE.com ...
WARNING:validate_email.validate_email:Validation for 'dan@retention360.com' failed: Email address undeliverable:
ALT1.ASPMX.L.GOOGLE.com: timed out
ALT2.ASPMX.L.GOOGLE.com: timed out
ASPMX2.GOOGLEMAIL.com: timed out
ASPMX3.GOOGLEMAIL.com: timed out
ASPMX.L.GOOGLE.com: timed out
False
(venv) Hs-MacBook-Pro:pythonProject4 hdanforthirwin$ 
```
Other things of note: 

I had a lot of trouble getting dnspython installed. Maybe its running, but not actually installed properly? It seems to work when I do a simple socket.gethostbyname_ex() though. 

![image](https://user-images.githubusercontent.com/68263827/102820351-1a9a9280-43a3-11eb-9ee3-540b388d460f.png)

Hunter.io has no problem verifying the email address: 

![image](https://user-images.githubusercontent.com/68263827/102820180-d3ac9d00-43a2-11eb-814c-6788359a48c4.png)

(On a 2017 MacBook Pro with Big Sur 11.1. PyCharm and Python 3.9. Tried it with both a VPN and no VPN)

**Comment by karolyi** [comment]
This seems to me that hostname resolution works, but google is blocking port 25 requests from your original IP address as well as VPN address.

To check, you can try and telnet to port 25 of any of those addresses listed above. In windows, this would be:
- opening a commandline window (win+R, cmd, enter)
- typing `telnet ALT1.ASPMX.L.GOOGLE.com 25` and see what gives.

**Comment by karolyi** [comment]
Oh, I forgot you have macos. There, the command specified above has to be run from within a terminal window.

**Comment by hdanirwin** [comment]
You were right --- it was my internet provider and my VPN that are blocking port 25 access. Interestingly, when I use my phone as a hotspot its fine. 

Can you recommend a VPS or VPN that doesn't block port 25?

**Comment by karolyi** [comment]
Not really. I use zenmate but I never tested it with this. I have my own servers for when I want to test.

**Comment by hdanirwin** [comment]
Well, I'm trying AWS's free tier right now and can't for the life of me
figure out which setting I'm missing. We'll see what their support says. If
that doesn't work I'll try zenmate. Either way I'll report back.

Thanks both for making this and for being so responsive!


------------------------------------------------------------------------------
Dan Irwin

(917) 533-3351

**Comment by karolyi** [comment]
AWS blocks port 25 in egress, it has been mentioned here somewhere in the closed issues. if you search for it, you'll find it.

**Comment by hdanirwin** [comment]
Nothing is easy....

**Comment by hdanirwin** [comment]
Update: Got it to work on AWS, just needed to ask them to open up port 25
(when asked why and what I would do to prevent spam abuse I was honest and
told them I wanted to use this package and would just turn off the instance
when not using)
------------------------------------------------------------------------------
Dan Irwin

(917) 533-3351

**Comment by karolyi** [comment]
Great stuff, thanks for adding your resolution.

If you deem this to be solved, please close the issue or wait 2 weeks until stalebot closes it.
