### ISSUE TITLE
No module named 'dns'

### ISSUE THREAD

**Issue by xbln** [karolyi/py3-validate-email#41]
I get a strange error message when applying your test code:

System: Windows 10 with Python 3.9
```
import logging, sys 
from validate_email import validate_email

logging.basicConfig(stream=sys.stderr, level=logging.DEBUG)
print(validate_email('martin.esche@gmx.de', check_mx=True, debug=False))
```
Log:
c:/Python39/Scripts/test.py
Traceback (most recent call last):
  File "c:\Python39\Scripts\test.py", line 2, in <module>
    from validate_email import validate_email
  File "C:\Users\marti\AppData\Local\Programs\Python\Python39\lib\site-packages\validate_email\__init__.py", line 1, in <module>
    from .validate_email import validate_email, validate_email_or_fail  # NOQA
  File "C:\Users\marti\AppData\Local\Programs\Python\Python39\lib\site-packages\validate_email\validate_email.py", line 8, in <module>
    from .mx_check import mx_check
  File "C:\Users\marti\AppData\Local\Programs\Python\Python39\lib\site-packages\validate_email\mx_check.py", line 7, in <module>
    from dns.exception import Timeout
ModuleNotFoundError: **No module named 'dns'**

**Comment by karolyi** [comment]
this indicates that the `dnspython` module (specified as a requirement in `setup.py`) is not installed. did you enter your virtual environment that you installed this module into, before testing?

**Comment by xbln** [comment]
dnspython is installed.

Traceback (most recent call last):
  File "c:\Python39\Scripts\test.py", line 2, in <module>
    from validate_email import validate_email
  File
"C:\Users\marti\AppData\Local\Programs\Python\Python39\lib\site-packages\validate_email\__init__.py",
line 1, in <module>
    from .validate_email import validate_email, validate_email_or_fail  #
NOQA
  File
"C:\Users\marti\AppData\Local\Programs\Python\Python39\lib\site-packages\validate_email\validate_email.py",
line 8, in <module>
    from .mx_check import mx_check
  File
"C:\Users\marti\AppData\Local\Programs\Python\Python39\lib\site-packages\validate_email\mx_check.py",
line 7, in <module>
    from dns.exception import Timeout
ModuleNotFoundError: No module named 'dns'
PS C:\Python39\Scripts> pip3 install dnspython

*Requirement already satisfied: dnspython in
c:\users\marti\appdata\local\programs\python\python39\lib\site-packages
(2.0.0)*

Best

Martin


Am Mi., 6. Jan. 2021 um 15:05 Uhr schrieb László Károlyi <
notifications@github.com>:

**Comment by karolyi** [comment]
what's the output of `python -m pip freeze`?

**Comment by xbln** [comment]
PS C:\Python39\Scripts> python -m pip freeze
astroid==2.4.2
certifi==2020.12.5
chardet==4.0.0
click==7.1.2
colorama==0.4.4
dnspython==2.0.0
fastapi==0.62.0
filelock==3.0.12
fpdf==1.7.2
h11==0.11.0
idna==2.10
isort==5.6.4
lazy-object-proxy==1.4.3
mccabe==0.6.1
paho-mqtt==1.5.1
pathlib==1.0.1
Pillow==8.0.1
py3-validate-email==0.2.12
pydantic==1.7.3
pylint==2.6.0
python-dotenv==0.15.0
pywin32==300
PyYAML==5.3.1
reportlab==3.5.56
requests==2.25.1
six==1.15.0
starlette==0.13.6
toml==0.10.2
urllib3==1.26.2
uvicorn==0.13.1
validate-email==1.3
watchgod==0.6
websockets==8.1
wrapt==1.12.1



Am Mi., 6. Jan. 2021 um 20:44 Uhr schrieb László Károlyi <
notifications@github.com>:

**Comment by karolyi** [comment]
that's odd.

are you sure the script you run uses the same python and the same virtual environment?

**Comment by xbln** [comment]
Yes. There is no venv.

[image: image.png]

Am Mi., 6. Jan. 2021 um 21:11 Uhr schrieb László Károlyi <
notifications@github.com>:

**Comment by karolyi** [comment]
what is the output of `python -c 'import dns; print(dns.__file__)'`?

**Comment by xbln** [comment]
PS C:\Python39\Scripts> python -c 'import dns; print(dns.__file__)'?
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'dns'
PS C:\Python39\Scripts>



Am Mi., 6. Jan. 2021 um 21:20 Uhr schrieb László Károlyi <
notifications@github.com>:

**Comment by karolyi** [comment]
can you paste the output of `dir C:\Users\marti\AppData\Local\Programs\Python\Python39\lib\site-packages\`?

**Comment by xbln** [comment]
Verzeichnis von
C:\Users\marti\AppData\Local\Programs\Python\Python39\lib\site-packages

06.01.2021  20:49    <DIR>          .
06.01.2021  20:49    <DIR>          ..
18.12.2020  20:42    <DIR>          adodbapi
18.12.2020  20:43    <DIR>          certifi
18.12.2020  20:43    <DIR>          certifi-2020.12.5.dist-info
18.12.2020  20:43    <DIR>          chardet
18.12.2020  20:43    <DIR>          chardet-4.0.0.dist-info
20.12.2020  02:47    <DIR>          click
20.12.2020  02:47    <DIR>          click-7.1.2.dist-info
06.01.2021  20:49    <DIR>          DNS
06.01.2021  01:57    <DIR>          dnspython-2.0.0.dist-info
20.12.2020  20:21    <DIR>          dotenv
18.12.2020  20:11               126 easy_install.py
20.12.2020  20:21    <DIR>          fastapi
20.12.2020  20:21    <DIR>          fastapi-0.62.0.dist-info
06.01.2021  01:57    <DIR>          filelock-3.0.12.dist-info
06.01.2021  01:57            13.229 filelock.py
19.12.2020  20:28    <DIR>          fpdf
19.12.2020  20:28    <DIR>          fpdf-1.7.2-py3.9.egg-info
20.12.2020  02:47    <DIR>          h11
20.12.2020  02:47    <DIR>          h11-0.11.0.dist-info
18.12.2020  20:43    <DIR>          idna
18.12.2020  20:43    <DIR>          idna-2.10.dist-info
18.12.2020  20:42    <DIR>          isapi
02.01.2021  12:49    <DIR>          paho
02.01.2021  12:49    <DIR>          paho_mqtt-1.5.1-py3.9.egg-info
18.12.2020  20:43    <DIR>          pathlib-1.0.1-py3.9.egg-info
03.09.2014  16:25            41.481 pathlib.py
19.12.2020  20:08    <DIR>          PIL
19.12.2020  20:08    <DIR>          Pillow-8.0.1.dist-info
18.12.2020  20:42    <DIR>          pip
18.12.2020  20:42    <DIR>          pip-20.3.3.dist-info
18.12.2020  20:11    <DIR>          pkg_resources
06.01.2021  01:57    <DIR>          py3_validate_email-0.2.12-py3.9.egg-info
20.12.2020  20:21    <DIR>          pydantic
20.12.2020  20:21    <DIR>          pydantic-1.7.3.dist-info
18.12.2020  20:42               138 pythoncom.py
18.12.2020  20:42    <DIR>          pythonwin
20.12.2020  20:21    <DIR>          python_dotenv-0.15.0.dist-info
18.12.2020  20:42    <DIR>          pywin32-300.dist-info
18.12.2020  20:42         2.666.406 PyWin32.chm
18.12.2020  20:42               178 pywin32.pth
18.12.2020  20:42                 5 pywin32.version.txt
18.12.2020  20:42    <DIR>          pywin32_system32
20.12.2020  20:21    <DIR>          PyYAML-5.3.1.dist-info
07.12.2020  18:12               121 README.txt
19.12.2020  20:08    <DIR>          reportlab
19.12.2020  20:08    <DIR>          reportlab-3.5.56.dist-info
18.12.2020  20:43    <DIR>          requests
18.12.2020  20:43    <DIR>          requests-2.25.1.dist-info
18.12.2020  20:11    <DIR>          setuptools
18.12.2020  20:11    <DIR>          setuptools-49.2.1.dist-info
20.12.2020  20:21    <DIR>          starlette
20.12.2020  20:21    <DIR>          starlette-0.13.6.dist-info
18.12.2020  20:43    <DIR>          urllib3
18.12.2020  20:43    <DIR>          urllib3-1.26.2.dist-info
20.12.2020  02:47    <DIR>          uvicorn
20.12.2020  02:47    <DIR>          uvicorn-0.13.1.dist-info
06.01.2021  01:57    <DIR>          validate_email
06.01.2021  01:18    <DIR>          validate_email-1.3-py3.9.egg-info
23.03.2015  05:22             8.340 validate_email.py
20.12.2020  20:20    <DIR>          watchgod
20.12.2020  20:21    <DIR>          watchgod-0.6.dist-info
20.12.2020  20:20    <DIR>          websockets
20.12.2020  20:20    <DIR>          websockets-8.1-py3.9.egg-info
18.12.2020  20:42    <DIR>          win32
18.12.2020  20:42    <DIR>          win32com
18.12.2020  20:42    <DIR>          win32comext
20.12.2020  20:21    <DIR>          yaml
20.12.2020  20:21           259.584 _yaml.cp39-win_amd64.pyd
06.01.2021  01:57    <DIR>          __pycache__
              10 Datei(en),      2.989.608 Bytes
              61 Verzeichnis(se), 155.285.016.576 Bytes frei



Am Mi., 6. Jan. 2021 um 21:56 Uhr schrieb László Károlyi <
notifications@github.com>:

**Comment by karolyi** [comment]
so for some weird reason, the `dns` module that `dnspython` installs, is installed most probably into that `DNS` directory (uppercase name), and so the module can't import it with lowercase name.

what's the content of

`C:\Users\marti\AppData\Local\Programs\Python\Python39\lib\site-packages\dnspython-2.0.0.dist-info\top_level.txt`,
`C:\Users\marti\AppData\Local\Programs\Python\Python39\lib\site-packages\dnspython-2.0.0.dist-info\RECORD` and 
`C:\Users\marti\AppData\Local\Programs\Python\Python39\lib\site-packages\dnspython-2.0.0.dist-info\METADATA`?

you could also try reinstalling the module into a new environment.

**Comment by xbln** [comment]
OK, thank you, Lázló!

If you say, the problem has nothing to do with your module, I am going to
reinstall the environment.

Thanks again for your help!

Best

Martin

Am Mi., 6. Jan. 2021 um 22:10 Uhr schrieb László Károlyi <
notifications@github.com>:
