### ISSUE TITLE
how many reuses can we do a minute / time periode before getting banned?

### ISSUE THREAD

**Issue by geniGit2921** [karolyi/py3-validate-email#43]
how many requests can we do a minute / time periode before getting banned?

**Comment by karolyi** [comment]
that's provider dependent. please don't use this module for abuse.

**Comment by geniGit2921** [comment]
i want to validate 150.000 email addresses slowly,

**Comment by geniGit2921** [comment]
what would be a safe rate u think?

**Comment by karolyi** [comment]
I can't give you a hint on that. every email provider draws their line differently. your best bet is a trial-and-error basis.

**Comment by geniGit2921** [comment]
ill try at 1 a second and see what happends

**Comment by bilal-athar** [comment]
@geniGit2921 have you tried to validate your emails?
