### ISSUE TITLE
No valid exception for knowing 'Access Denied'

### ISSUE THREAD

**Issue by voxvici** [karolyi/py3-validate-email#44]
Exception 'AddressNotDeliverableError' is thrown both for when a server is blocked/denied and when email doesn't exist.

Gmail allows local testing if you run the following code

```
try:
    is_valid = validate_email_or_fail(email_address='this.is.my.name.new.name3@gmail.com', check_regex=False, check_mx=True, use_blacklist=True, debug=True)
except Exception as ex:
    message = f"An exception of type {type(ex).__name__} occurred. Arguments:\n{ex.args}"
    print(message)
```

Inside Debug Log it will emit 'The email account that you tried to reach does not exist'

Outlook disallows local testing if you run the following code

```
try:
    is_valid = validate_email_or_fail(email_address='this.is.my.name.new.name3@primaplan.nl', check_regex=False, check_mx=True, use_blacklist=True, debug=True)
except Exception as ex:
    message = f"An exception of type {type(ex).__name__} occurred. Arguments:\n{ex.args}"
    print(message)
```

Inside Debug Log it will emit 'Access denied, banned sending IP'

'AddressNotDeliverableError' exception cannot be both if a server got blocked and email doesn't exist.

**Comment by voxvici** [comment]
Is it possible to access Debug object?

**Comment by manojr2k** [comment]
i am also interested to know the above error handling , since my code not able to understand the error code for block ip

**Comment by karolyi** [comment]
@voxvici you just have to simply use the `validate_email_or_fail()` function, which will raise an exception that you catch and the error message will be in the exception arguments.

**Comment by reinhard-mueller** [comment]
@manojr2k @voxvici Out of curiosity, may I ask what you would consider the best behavior in the case of such an "Access denied" (or other messages about blacklisting or similar issues)?

Would it be sufficient if the result of the function was just `None` like in other cases where there is no verification possible (like mail server down, greylisting etc), and you can look at the debug log what was the reason for not being able to give a clear result? Or would you still need access to the error messages to programmatically react different to the various reasons that can lead to a `None` result? Or would you think an additional exception should be introduced saying "you're blacklisted"?

**Comment by manojr2k** [comment]
There should be some unique id  which we can identify in the code and take
the necessary action

**Comment by manojr2k** [comment]
any update  reinhard ?

**Comment by reinhard-mueller** [comment]
@manojr2k sorry I don't think that I will have an implementation proposal in short time, I need to think more about this, but your feedback is appreciated as input for that.

**Comment by voxvici** [comment]
@reinhard-mueller
apologizes for not answering been busy with work, I've found a workaround solution for the blacklist issue ideally a blacklist exception but I've read some of the @karolyi comments before and he was talking it's hard to know when the server actually is blacklisted? if I remember correctly. It would be nice to have an additional exception due to logging and knowing what is internally happening, maybe tuple returning debug message with status code? always nice to have
