### ISSUE TITLE
MX check on private domain fails

### ISSUE THREAD

**Issue by mfpx** [karolyi/py3-validate-email#47]
Hi,
I have an issue where running validate_email on my private email address does not work. I am able to successfully verify public domain addresses (i.e. @gmail.com etc)

So, if I run validate_email on any addresses @stumbra.co.uk (my personal domain), it can find the MX records, but it appears that its telnet attempts fail.

Input:
`>>> print(validate_email('david@stumbra.co.uk', check_mx=True, debug=True))`

Result:
`DEBUG:validate_email.mx_check:Trying hermes.hosts.co.uk ...`
`DEBUG:validate_email.mx_check:Trying athena.hosts.co.uk ...`
`None`

The issue appears to be that it cannot connect to them over telnet, and excluding domains where telnet fails with `check_mx` flag doesn't make sense. While I could do a check where if `validate_email` returns `None` to run it without the `check_mx` flag, I feel like that could lead to false positives.

Any advice/suggestions?

**Comment by karolyi** [comment]
I'm not sure what your issue is here.

Upon trying to connect to port 25 of the hosts you specified, the connection opens but there is no welcome message from the SMTP server. That is a problem, because the protocol starts with a server greeting.

This is nothing the module can fix.

**Comment by karolyi** [comment]
With further tests from my own server (that is a qualified mail delivery server) it seems that the mail servers you use won't even greet hosts with that are in IP pools or blocklists (the two are often a union of the same IP addresses).

This means, even if the port is not blocked from your local IP, the server will refuse to talk to it. Again, this is nothing I can fix, it's always up to your network situation and the configuration of the remote server.

**Comment by reinhard-mueller** [comment]
@mfpx I just tried out of curiosity and now your mail servers seem to send a proper greeting. Did you change anything? Does it work now for you?

**Comment by mfpx** [comment]
@reinhard-mueller No, I don't have any access to the mail servers, they're run by my hosting provider - running my own servers at home would be too costly

**Comment by reinhard-mueller** [comment]
I again tried and I can telnet to both servers with port 25. There seems to be some security setting on these mail servers that forbid you to use them. What py3-validate-email sees is two non-functional mail servers, so the test result that the email addresses are not reachable (from your environment) is correct.

I guess that your hosting provider blocks some IP address ranges, for example dynamically assigned IP addresses. I guess you'll need to make your tests from a different IP which is not blocked by your hosting provider.

**Comment by karolyi** [comment]
see https://github.com/karolyi/py3-validate-email/issues/47#issuecomment-775873399
