### ISSUE TITLE
It's Not Checking Yahoo Email

### ISSUE THREAD

**Issue by Hamza-Lachi** [karolyi/py3-validate-email#5]
Hi I Tried This Module But It Only Work For Gmail It's Not Working On Yahoo,Outlook,hotmail

here is the code

`validation = validate_email(email_address=str(df[i]).replace(',','').replace(';',''),check_regex=True,check_mx=True, from_address='', helo_host='', smtp_timeout=30, dns_timeout=30, use_blacklist=True)`

**Comment by karolyi** [comment]
you have to use a proper `from_address` and `helo_host`.

**Comment by mohanarunachalam** [comment]
Hi,
I am facing this same issue. I am trying to test validity of an Yahoo email. Many online tools say, the email is False or the 'mailbox not found error'.
But, the library says 'True'.
Could you please explain if I am missing something?

Also, what are the values to pass for from_address and helo_host?
I tried passing from_address='my_gmail_address' and helo_host='gmail.com' , but still it returned True.

**Comment by karolyi** [comment]
If you get `True`, that means yahoo's servers in the SMTP conversation said they would accept the email coming from that address, going to the address you passed in the "to" parameter. Not much I can do there, yahoo does this probably to provide false positives for spammers testing for emails to spam. Or you might have hit an MX that will try to relay every email to yahoo's servers.

Look into the SMTP protocol to understand what the HELO command does, but basically you should use your IP's fully qualified domain name.

**Comment by karolyi** [comment]
On a second thought, there's something off. I'll look into this later.

**Comment by mohanarunachalam** [comment]
Thanks for the immediate reply. Will do further rounds of testing and look out for any relevant info. on this.

**Comment by karolyi** [comment]
@mohanarunachalam see https://github.com/karolyi/py3-validate-email#the-module-provides-false-positives

**Comment by mohanarunachalam** [comment]
Ok. Thanks for the update. Really helpful.
