### ISSUE TITLE
Limited Emails

### ISSUE THREAD

**Issue by SergeyKons** [karolyi/py3-validate-email#53]
Hi!
We found some issues with organization emails located on google suite.

Some accounts in these organizations cannot send or receive emails. So if we try to send a registration email on it, we get a bounce on AWS SES.

How do you think, is there any way to check these email addresses?

There are parts of some AWS bounce notifications:

```
[{"emailAddress":"MASKEDUSEREMAIL","action":"failed","status":"5.7.1","diagnosticCode":"smtp; 550-5.7.1 This message has been rejected as this student is not able to send or\n550 5.7.1 receive external mail. - gcdp g5si1130787uad.263 - gsmtp"}],"timestamp":"2021-02-18T16:49:33.000Z","remoteMtaIp":"173.194.209.27",
```

`smtp; 550-5.7.1 Sorry, sending email outside of the CBE Google Apps domain,\n550-5.7.1 @educbe.ca, is not permitted for staff accounts, exceptions are`

There is debug log of validate_email call (was done locally):

```
21:07:36.120543 connect: ('alt2.aspmx.l.google.com', 25)
21:07:36.120646 connect: to ('alt2.aspmx.l.google.com', 25) None
21:07:36.608010 reply: b'220 mx.google.com ESMTP m22si5637782pgu.215 - gsmtp\r\n'
21:07:36.608090 reply: retcode (220); Msg: b'mx.google.com ESMTP m22si5637782pgu.215 - gsmtp'
21:07:36.608132 connect: b'mx.google.com ESMTP m22si5637782pgu.215 - gsmtp'
21:07:36.608164 send: 'ehlo my.host.name\r\n'
21:07:36.864789 reply: b'250-mx.google.com at your service, [85.26.165.2]\r\n'
21:07:36.864890 reply: b'250-SIZE 157286400\r\n'
21:07:36.864920 reply: b'250-8BITMIME\r\n'
21:07:36.864947 reply: b'250-STARTTLS\r\n'
21:07:36.864972 reply: b'250-ENHANCEDSTATUSCODES\r\n'
21:07:36.864997 reply: b'250-PIPELINING\r\n'
21:07:36.865021 reply: b'250-CHUNKING\r\n'
21:07:36.865045 reply: b'250 SMTPUTF8\r\n'
21:07:36.865077 reply: retcode (250); Msg: b'mx.google.com at your service, [85.26.165.2]\nSIZE 157286400\n8BITMIME\nSTARTTLS\nENHANCEDSTATUSCODES\nPIPELINING\nCHUNKING\nSMTPUTF8'
21:07:36.865794 send: 'STARTTLS\r\n'
21:07:37.091898 reply: b'220 2.0.0 Ready to start TLS\r\n'
21:07:37.092001 reply: retcode (220); Msg: b'2.0.0 Ready to start TLS'
21:07:37.353562 send: 'ehlo my.host.name\r\n'
21:07:37.844762 reply: b'250-mx.google.com at your service, [85.26.165.2]\r\n'
21:07:37.844877 reply: b'250-SIZE 157286400\r\n'
21:07:37.844919 reply: b'250-8BITMIME\r\n'
21:07:37.844954 reply: b'250-ENHANCEDSTATUSCODES\r\n'
21:07:37.844987 reply: b'250-PIPELINING\r\n'
21:07:37.845018 reply: b'250-CHUNKING\r\n'
21:07:37.845054 reply: b'250 SMTPUTF8\r\n'
21:07:37.845114 reply: retcode (250); Msg: b'mx.google.com at your service, [85.26.165.2]\nSIZE 157286400\n8BITMIME\nENHANCEDSTATUSCODES\nPIPELINING\nCHUNKING\nSMTPUTF8'
21:07:37.845492 send: 'mail FROM:<my@from.addr.ess>\r\n'
21:07:38.090705 reply: b'250 2.1.0 OK m22si5637782pgu.215 - gsmtp\r\n'
21:07:38.090835 reply: retcode (250); Msg: b'2.1.0 OK m22si5637782pgu.215 - gsmtp'
21:07:38.091075 send: 'rcpt TO:<MASKEDUSEREMAIL>\r\n'
21:07:39.053906 reply: b'250 2.1.5 OK m22si5637782pgu.215 - gsmtp\r\n'
21:07:39.054053 reply: retcode (250); Msg: b'2.1.5 OK m22si5637782pgu.215 - gsmtp'
21:07:39.054121 send: 'QUIT\r\n'
21:07:39.282447 reply: b'221 2.0.0 closing connection m22si5637782pgu.215 - gsmtp\r\n'
21:07:39.282578 reply: retcode (221); Msg: b'2.0.0 closing connection m22si5637782pgu.215 - gsmtp'
```

Script i was used for testing

```python
from validate_email.validate_email import validate_email
import argparse

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("email", metavar="email")

    args = parser.parse_args()

    is_valid = validate_email(
        email_address=args.email,
        check_regex=True,
        check_mx=True,
        from_address="my@from.addr.ess",
        helo_host="my.host.name",
        smtp_timeout=10,
        dns_timeout=10,
        use_blacklist=True,
        debug=True,
    )

    print(f'RESULT: {"Valid" if is_valid else "InValid"}')
```

**Comment by reinhard-mueller** [comment]
Can you check which action caused the AWS bounce? It's usually mentioned in the bounce (like: "in reply to MAIL FROM" or something similar). I also made the experience that sometimes, mails are accepted first, but then after some hours a bounce is created. In such a case there's no way to automatically test.

**Comment by SergeyKons** [comment]
My colleague will write here more info about bounce today.

**Comment by karolyi** [comment]
The bounces in this case are coming from a program that handles delivery after the SMTP conversation is done.

For example, I can setup an "umbrella" domain that will forward every emails to a given script that will handle deliveries locally after it's got the email body (after the aforementioned SMTP conversation is done).

This module is for exclusively checking the SMTP part, hence there is no way to handle the bounces that come from something afterwards.

**Comment by ihor-tkachenko** [comment]
> Can you check which action caused the AWS bounce? It's usually mentioned in the bounce (like: "in reply to MAIL FROM" or something similar). I also made the experience that sometimes, mails are accepted first, but then after some hours a bounce is created. In such a case there's no way to automatically test.

> The bounces in this case are coming from a program that handles delivery after the SMTP conversation is done.
> 
> For example, I can setup an "umbrella" domain that will forward every emails to a given script that will handle deliveries locally after it's got the email body (after the aforementioned SMTP conversation is done).
> 
> This module is for exclusively checking the SMTP part, hence there is no way to handle the bounces that come from something afterwards.

Hello!
Here is the text of the bounce message for one of our recipients. And you are correct, this cannot be verified before the actual mail is sent. Thank you for your time.

`Message blocked Your message sent to RECIPIENT_ADDRESS has been blocked. See technical details below.
550 5.7.1 OCPS student accounts are not able to receive emails from external domains. - gcdp y23sor2507753uaq.55 - gsmtp`

**Comment by SergeyKons** [comment]
Ok, I think we cannot find a solution here so we can close this issue
