### ISSUE TITLE
waiting for update

### ISSUE THREAD

**Issue by manojr2k** [karolyi/py3-validate-email#54]
waiting for update

_Originally posted by @manojr2k in https://github.com/karolyi/py3-validate-email/issues/46#issuecomment-781905545_

**Comment by reinhard-mueller** [comment]
@manojr2k version 0.2.16 should already contain that change. Can you check whether it works for you?

**Comment by karolyi** [comment]
please refrain from opening new issues senselessly.

besides, we all do this project on a free time basis, of which we don't have a lot. PRs are welcome though.
