### ISSUE TITLE
Outdated dependencies

### ISSUE THREAD

**Issue by reinhard-mueller** [karolyi/py3-validate-email#65]
py3-validate-email requires specific versions of its dependencies, but for two of them newer versions would be available:
* dnspython: 2.0 required, 2.1 available
* idna: 2.10 required, 3.1 available
Maybe the requirements list should be updated before the release. From a look at the version statistics, none of the updates seems to contain any change relevant for us.

**Comment by reinhard-mueller** [comment]
Sorry, I just learned that "dnspython~=2.0" actually means "2.x with x>=0". So it would only have to be updated for idna.

**Comment by karolyi** [comment]
Yeah, I did those to avoid pulling major versions. Do you see idna3.1 having any breaking changes?

**Comment by reinhard-mueller** [comment]
According to [the release history](https://github.com/kjd/idna/blob/master/HISTORY.rst) the only breaking change is the drop of support for Python 2, which we don't care about.

**Comment by karolyi** [comment]
1.0.0 is out now, thank you again for your help!
