### ISSUE TITLE
Suggestions about the validation

### ISSUE THREAD

**Issue by Erica-Ko** [karolyi/py3-validate-email#66]
Dear contributors, I have the following suggestions after I made my research about other email validation API:
1) Detection of the catch-all property of the email server
2) email spam traps detection
I am not sure how to do these functions so I can't make a PR, if you know and share any resources about how to implement it, I can implement it for the project as well
Thank you

**Comment by karolyi** [comment]
1: not sure what you are looking for, you will need to elaborate on this
2: the blacklist functionality this module provides is already what you are talking about  imo.

If not, please list your needs in a detailed way. From what I can take away from your comment, nothing's needed to be done.
