### ISSUE TITLE
[Errno 30] Read-only file system

### ISSUE THREAD

**Issue by airmonitor** [karolyi/py3-validate-email#7]
Hello.

Thx for your library :)

I'm using your module in the AWS Lambda. There are some limitations there, one of them is that the filesystem is R/O with exception to the /tmp dir.

When I ran:
`validate_email(email_address=sender_email, check_regex=True, check_mx=True, dns_timeout=10, use_blacklist=True)`

got:
`[Errno 30] Read-only file system: '/opt/python/lib/python3.8/site-packages/validate_email/data'`

Is there any way to specify temporary dir or maybe keep this in memory?

Regards

**Comment by karolyi** [comment]
Hi,

this is related to #6, I'm going to address this issue there.
