### ISSUE TITLE
[SUGGESTION] idna dependency

### ISSUE THREAD

**Issue by ohelal** [karolyi/py3-validate-email#71]
Thank you for the great work on this library, it's tremendous.

I'd like to make a suggestion to change the idna dependency version to <=3 rather than ~=3

The reason for this is when using dependency resolvers like pip-tools, this currently causes a dependency conflict with the popular requests library which capped it's idna dependency to idna<3

Thank you for your consideration

**Comment by karolyi** [comment]
Hey,

yes I know about this problem, it's actually blocking me too from upgrading one of my projects where I use this module in.

Requests will fix this in 2.26.0, so hold on for a little bit longer, the release is already tagged: https://github.com/psf/requests/pull/5711

**Comment by ohelal** [comment]
Yeah I was looking at that earlier,
Thanks for the heads up and the consideration

**Comment by MRB60** [comment]
On ubuntu 20.04 with python3, I get the following issue. Can it be fixed or does anyone have a work-around for me?
`ERROR: requests 2.25.0 has requirement idna<3,>=2.5, but you'll have idna 3.2 which is incompatible.`

**Comment by karolyi** [comment]
if you install requests, you'll get the error.

they need to fix their shit already.
