### ISSUE TITLE
password for smtp_from_address

### ISSUE THREAD

**Issue by alpkeskin** [karolyi/py3-validate-email#73]
I want to use my own Gmail account for `smtp_from_address`. Also, if I'm going to use my own Gmail account, I need to enter a password and Gmail's smtp port. But when I look at the parameters, there are no parameters for the port or password.

**Comment by reinhard-mueller** [comment]
See in the FAQ: https://github.com/karolyi/py3-validate-email/blob/master/FAQ.md#how-can-i-pass-my-email-accounts-credentials-how-can-i-use-port-465-or-587-when-my-provider-blocks-port-25
