### ISSUE TITLE
pip install py3-validate-email doesn't seem to work for me

### ISSUE THREAD

**Issue by karolyi** [karolyi/py3-validate-email#77]
### Discussed in https://github.com/karolyi/py3-validate-email/discussions/76

<div type='discussions-op-text'>

<sup>Originally posted by **ikumaruku** August 11, 2021</sup>
in detail, i have an error dowloading the blacklist file
'downloading blacklist to /private/var/folders/g2/1zfp4ykd7xs_pj4d47fjsbn00000gn/T/pip-install-kziyx6ue/py3-validate-email/build/lib/validate_email/data/blacklist.txt
    error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)>'
says that certificate verify failed. any ideas?
</div>

@ikumaruku, you opened a discussion topic for an issue. moreover, the solution is [one search away](https://github.com/karolyi/py3-validate-email/issues?q=is%3Aissue+CERTIFICATE_VERIFY_FAILED+is%3Aclosed) from you.

**Comment by makdosdogancan** [comment]
because of that martenson's project was dead.

https://raw.githubusercontent.com/martenson/disposable-email-domains/

**Comment by karolyi** [comment]
[No, it's not.](https://raw.githubusercontent.com/martenson/disposable-email-domains/master/disposable_email_blocklist.conf)
