### ISSUE TITLE
validate_email always returns None

### ISSUE THREAD

**Issue by ankurgla22** [karolyi/py3-validate-email#78]
> from validate_email import validate_email
> verify = validate_email('ankurgla44@gmail.com', smtp_debug=True)
> print(verify)

Ouput: None

Validate_email always returns None. I have tested with multiple valid emails

> 11:57:46.175698 connect: ('gmail-smtp-in.l.google.com', 25)
11:57:46.175862 connect: to ('gmail-smtp-in.l.google.com', 25) None
11:57:56.280967 send: 'quit\r\n'
11:57:56.280967 connect: ('alt1.gmail-smtp-in.l.google.com', 25)
11:57:56.284559 connect: to ('alt1.gmail-smtp-in.l.google.com', 25) None
11:58:06.396366 send: 'quit\r\n'
11:58:06.396366 connect: ('alt2.gmail-smtp-in.l.google.com', 25)
11:58:06.402360 connect: to ('alt2.gmail-smtp-in.l.google.com', 25) None
11:58:16.528653 send: 'quit\r\n'
11:58:16.528653 connect: ('alt3.gmail-smtp-in.l.google.com', 25)
11:58:16.531664 connect: to ('alt3.gmail-smtp-in.l.google.com', 25) None
11:58:26.660083 send: 'quit\r\n'
11:58:26.660083 connect: ('alt4.gmail-smtp-in.l.google.com', 25)
11:58:26.664988 connect: to ('alt4.gmail-smtp-in.l.google.com', 25) None
11:58:36.767845 send: 'quit\r\n'
None

**Comment by karolyi** [comment]
The included issue template with a link was there for a reason. Please read it carefully and come back to me when you are able to produce a debug output described by the commands there.

Closing this.
