### ISSUE TITLE
Problem with GMAIL checking

### ISSUE THREAD

**Issue by BacharSouhail** [karolyi/py3-validate-email#82]
from validate_email import validate_email
is_valid = validate_email(
    email_address='xxxxxx@gmail.com',
    check_format=False,
    check_blacklist=True,
    check_dns=True,
    dns_timeout=10,
    check_smtp=True,
    smtp_timeout=10,
    smtp_skip_tls=False,
    smtp_tls_context=None,
    smtp_debug=False)

print(is_valid)

#Always returns None

**Comment by karolyi** [comment]
You clearly didn't read the FAQ. Please do and try again.

**Comment by BacharSouhail** [comment]
> You clearly didn't read the FAQ. Please do and try again.

Which part exactly?

**Comment by BacharSouhail** [comment]
Like everything was fine but I don't really know what happened
