### ISSUE TITLE
Different parts of the code use different methods to do the same thing

### ISSUE THREAD

**Issue by reinhard-mueller** [karolyi/py3-validate-email#9]
When looking through the code, I noticed that sometimes the same task is done in different ways:

* `mx_check` uses `EMAIL_EXTRACT_HOST_REGEX` to split the email address into user and domain, while `validate_email` uses a simple `rsplit('@', 1)`.
* `mx_check` uses the `idna` library to resolve IDNA hostnames, while `validate_email` uses a simple `encode('idna')`.

I could find no reason to not always use the simple method, which probably would make the code more understandable.

**Comment by reinhard-mueller** [comment]
An additional idea: because sometimes the split parts are needed and sometimes the full address, sometimes the idna resolved version is wanted and sometimes the original version - how about creating a small helper class that works like this:
```python
>>> email = EmailAddress('drummer@motörhéád.com')
>>> print(email)
'drummer@motörhéád.com'
>>> print(email.user)
'drummer'
>>> print(email.domain)
'motörhéád.com'
>>> print(email.ace)
'drummer@xn--motrhd-tta7d3f.com'
>>> print(email.ace_domain)
'xn--motrhd-tta7d3f.com'
```
This would make it possible to have all the magic to split and convert email addresses in one place.

**Comment by karolyi** [comment]
Useful insights, your second PR is welcome :) Mind you I'm probably updating the updater tomorrow, but you can work on these ideas meanwhile.

**Comment by karolyi** [comment]
FYI, I just tested the difference between the idna library and the built-in `.encode('idna')`. It seems that the idna library provides extra validation for the domains which I would keep.

Keep the PR coming with the `EmailAddress` class :)

**Comment by reinhard-mueller** [comment]
Thank you for testing, this is very helpful! I plan to submit a PR today, although I can't promise 100% it'll be read before the evening. Anyway, stay tuned :-)

**Comment by karolyi** [comment]
Refs #11
